### ISSUE TITLE
bad argument (expected URI object or URI string)

### ISSUE THREAD

**Issue by silkcom** [ejholmes/restforce#234]
I'm running in rails console with the following code:

    client = Restforce.new :username => 'RANDOM@EMAIL.sandbox', :password => 'my password', :api_version => "34.0"
    client.describe

and I get the following error:

ArgumentError: bad argument (expected URI object or URI string)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/utils.rb:260:in `URI'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/faraday-0.9.2/lib/faraday/connection.rb:309:in `url_prefix='
        from /usr/local/rvm/gems/ruby-2.2.1/gems/restforce-2.1.2/lib/restforce/concerns/verbs.rb:39:in `rescue in block in define_verb'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/restforce-2.1.2/lib/restforce/concerns/verbs.rb:34:in `block in define_verb'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/restforce-2.1.2/lib/restforce/concerns/verbs.rb:61:in `block in define_api_verb'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/restforce-2.1.2/lib/restforce/concerns/api.rb:106:in `describe'
        from (irb):7
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
        from /home/cstep/r2/bin/rails:8:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by OddEssay** [comment]
I've hit this exact problem - It's unclear if this is an actual bug, or perhaps there are some assumptions in the usage that aren't clearly documented in the README?

**Comment by timrogers** [comment]
Have either of you had a chance to do some digging into this? I think it'll
be quite easy to find the cause with some digging into the stack trace, but
I'm a little busy right now.

--

*Tim Rogers*
GoCardless.com <https://gocardless.com>

**Comment by lcpriest** [comment]
I had this issue unless I included the instance_url.

**Comment by antwonlee** [comment]
Perhaps the Readme can be updated?  I get similar errors when run in console.

**Comment by timrogers** [comment]
Fancy tweaking it for yourself in a PR? 👌

**Comment by voodoologic** [comment]
I added 'https://'  to the url string and that solves the issue for me.

**Comment by Shwetakale** [comment]
@timrogers I am using ```restforce```  version ```2.1.0``` and I don't see this issue. I followed steps specified in above issue.

(here)[https://github.com/ejholmes/restforce/blob/master/lib/restforce/concerns/base.rb#L64] if instance_url is not present then authentication is done and instance_url is set on the client.

But if ```client_id``` and ```client_secret``` are ```nil``` then that produces above issue.

 
![rsz_restforce1](https://cloud.githubusercontent.com/assets/6301532/16440113/7aac76ce-3ddc-11e6-8dd9-e2af553d5c17.png)

And in (documentation)[https://github.com/ejholmes/restforce/blob/master/lib/restforce/concerns/base.rb#L64] if you are using password authentication then this is specified.

So I think we can close this issue. Your thoughts?

**Comment by shadowbq** [comment]
@Shwetakale What is specified? The client_id and client_secret are not explained.

**Comment by shadowbq** [comment]
#        :client_id               - The oauth client id to use. Needed for both
      #                                   password and oauth authentication
      #        :client_secret           - The oauth client secret to use.

These should be explained on the README. 

Client vs Connected App.. Are these the same?

To connect to Salesforce you need to define a Connected App in a Salesforce account. 

Follow the instructions to create your [Connect App](https://help.salesforce.com/apex/HTViewHelpDoc?id=connected_app_create.htm). The Connected App creates an Oauth consumer key and secret which you need to authenticate to the force.com API.

Once you create Connected App inside of one Salesforce account, your app can access any Salesforce acccount using the same Oauth credentials.

**Comment by timrogers** [comment]
@shadowbq Do you want to make a PR adding something useful to the README?

**Comment by timrogers** [comment]
Are you able to provide a minimal reproduction?
