### ISSUE TITLE
get_updated() always returns Faraday::ResourceNotFound: NOT_FOUND: The requested resource does not exist

### ISSUE THREAD

**Issue by jeremymburton** [ejholmes/restforce#235]
I am able to retrieve objects and can see their LastModifiedDate using find(), etc.

However, If I call get_updated(), specifying a date range that includes objects that I know to be in that range, it always returns:

Faraday::ResourceNotFound: NOT_FOUND: The requested resource does not exist

Full trace:
```
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/middleware/raise_error.rb:13:in `on_complete'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/middleware/instance_url.rb:9:in `call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/middleware/authorization.rb:9:in `call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/middleware/authentication.rb:13:in `call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday_middleware-0.10.0/lib/faraday_middleware/request/encode_json.rb:23:in `call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/middleware/multipart.rb:14:in `call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/middleware/mashify.rb:6:in `call'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/concerns/verbs.rb:35:in `block in define_verb'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/concerns/verbs.rb:61:in `block in define_api_verb'
	from /Users/jeremyburton/.rvm/gems/ruby-2.1.5/gems/restforce-2.2.0/lib/restforce/concerns/api.rb:84:in `get_updated'
```

**Comment by jeremymburton** [comment]
Update:
It was an API version mismatch.

However, there is still the issue that this should be raising APIVersionError if you're using a version the API that doesn't support get_updated() rather than NotFound (although I'm guessing it's Salesforce itself that is at fault here).

**Comment by Shwetakale** [comment]
@jeremymburton You are right. This error is coming from salesforce as against that version api does not exist. So I don't think ```APIVersionMismatch``` can be raised when such type of error occurs.
