### ISSUE TITLE
Error code not detected when exception is generated in Salesforce

### ISSUE THREAD

**Issue by hansondr** [ejholmes/restforce#291]
I'm receiving a `Faraday::ClientError: (error code missing)` when handling an exception generated in a custom APEX class.  I'm using the following in Salesforce for testing:

```
@RestResource(urlMapping='/exception_testing/*')
global without sharing class REST_ExceptionTesting {
  @HttpPost
  global static void post(String stuff) {
    RestResponse response = RestContext.response;
    if (response == null) {
      response = new RestResponse();
      RestContext.response = response;
    }

    try {
      response.responseBody = Blob.valueOf(JSON.serialize(doPost(stuff)));
      response.statusCode = 200;
    } catch (EndUserMessageException e) {
      response.responseBody = Blob.valueOf(e.getMessage());
      response.statusCode = 400;
    } catch (Exception e) {
      response.responseBody = Blob.valueOf(
        String.valueOf(e) + '\n\n' + e.getStackTraceString()
      );
      response.statusCode = 500;
    }
  }

  private static Object doPost(String stuff) {
    if (stuff == 'boom') {
      throw new EndUserMessageException('User exception, should be a 400 status');
    }

    return stuff;
  }

  private class EndUserMessageException extends Exception {}
}
```

when I pass any string other than "boom" I receive:

```
client.post('/services/apexrest/exception_testing', stuff: 'booms')
=> #<Faraday::Response:0x0055bcc0f74540 @on_complete_callbacks=[], @env=#<Faraday::Env @method=:post @body="\"booms\"" @url=#<URI::HTTPS https://cs7.salesforce.com/services/apexrest/exception_testing> @request=#<Faraday::RequestOptions (empty)> @request_headers={"User-Agent"=>"Faraday v0.9.2", "Content-Type"=>"application/json", "Authorization"=>"OAuth SNIP"} @ssl=#<Faraday::SSLOptions verify=true> @response=#<Faraday::Response:0x0055bec0f74540 ...> @response_headers={"date"=>"Tue, 28 Feb 2017 16:22:13 GMT", "content-security-policy-report-only"=>"default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src https: data:; font-src https: data:; connect-src 'self' https:; report-uri /_/ContentDomainCSP?type=appserver", "x-xss-protection"=>"1; mode=block", "content-security-policy"=>"reflected-xss block;report-uri /_/ContentDomainCSPNoAuth?type=xss, referrer origin-when-cross-origin", "set-cookie"=>"BrowserId=45qH7vx3TCeD72UOOQ3KSA;Path=/;Domain=.salesforce.com;Expires=Sat, 29-Apr-2017 16:22:13 GMT", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "content-type"=>"application/octetstream", "transfer-encoding"=>"chunked", "connection"=>"close"} @status=200>>
```

and when passing "boom"

```
client.post('/services/apexrest/exception_testing', stuff: 'boom')
Faraday::ClientError: (error code missing): User exception, should be a 400 status
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/restforce-2.5.0/lib/restforce/middleware/raise_error.rb:18:in `on_complete'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:78:in `perform_with_redirection'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/response/follow_redirects.rb:66:in `call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/restforce-2.5.0/lib/restforce/middleware/instance_url.rb:9:in `call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/restforce-2.5.0/lib/restforce/middleware/authorization.rb:9:in `call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/restforce-2.5.0/lib/restforce/middleware/authentication.rb:13:in `call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday_middleware-0.11.0.1/lib/faraday_middleware/request/encode_json.rb:24:in `call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/restforce-2.5.0/lib/restforce/middleware/multipart.rb:14:in `call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/restforce-2.5.0/lib/restforce/middleware/mashify.rb:6:in `call'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /home/dev/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/restforce-2.5.0/lib/restforce/concerns/verbs.rb:35:in `block in define_verb'
	from (irb):20
	from /home/dev/.rbenv/versions/2.3.3/bin/irb:11:in `<main>'
```

and the associated `:debug` level log

```
D, [2017-02-28T09:23:33.903339 #23914] DEBUG -- request: 
  url: "https://cs7.salesforce.com/services/apexrest/exception_testing"
  method: :post
  headers: {"User-Agent"=>"Faraday v0.9.2", "Content-Type"=>"application/json", "Authorization"=>"OAuth SNIP"}
  body: "{\"stuff\":\"boom\"}"
D, [2017-02-28T09:23:34.469963 #23914] DEBUG -- response: 
  status: "400"
  headers: {"date"=>"Tue, 28 Feb 2017 16:23:34 GMT", "content-security-policy-report-only"=>"default-src https:; script-src https: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; img-src https: data:; font-src https: data:; connect-src 'self' https:; report-uri /_/ContentDomainCSP?type=appserver", "x-xss-protection"=>"1; mode=block", "content-security-policy"=>"reflected-xss block;report-uri /_/ContentDomainCSPNoAuth?type=xss, referrer origin-when-cross-origin", "set-cookie"=>"BrowserId=hr8p6CT1QqyZzbDnAjgoqQ;Path=/;Domain=.salesforce.com;Expires=Sat, 29-Apr-2017 16:23:34 GMT", "expires"=>"Thu, 01 Jan 1970 00:00:00 GMT", "content-type"=>"application/octetstream", "transfer-encoding"=>"chunked", "connection"=>"close"}
  body: "User exception, should be a 400 status"
```

**Comment by Woooddddooogggg** [comment]
I know it's been a while, but I'm stuck. Any luck getting past this @hansondr ?

**Comment by batshoes** [comment]
Me too, This has been blocking me for a little while. SF makes no mention of it.
